# Generated by Django 2.2.5 on 2021-11-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20211110_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
