# Generated by Django 2.2.5 on 2021-11-13 09:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211113_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=100, null=True),
        ),
    ]
