# Generated by Django 2.2.5 on 2021-11-13 09:15

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211113_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='authentication/profile_photos/default.png', force_format=None, keep_meta=True, null=True, quality=100, size=[50, 80], upload_to='authentication/profile_photos'),
        ),
    ]
