# Generated by Django 2.2.5 on 2021-11-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20211113_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='authentication/profile_photos/default.png', null=True, upload_to='authentication/profile_photos'),
        ),
    ]
