# Generated by Django 2.2.5 on 2021-11-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20211113_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='media/authentication/profile_photos/default.png', upload_to='authentication/profile_photos'),
        ),
    ]
