# Generated by Django 2.2.5 on 2021-11-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20211113_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='authentication/profile_photos/default.png', upload_to='authentication/profile_photos'),
        ),
    ]
