# Generated by Django 2.2.5 on 2021-11-13 10:23

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20211113_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='authentication/profile_photos/default.png', upload_to=authentication.models.get_filename),
        ),
    ]
