# Generated by Django 2.2.5 on 2021-11-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20211113_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='points',
            new_name='assignment_credits',
        ),
        migrations.AddField(
            model_name='account',
            name='course_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='forum_credits',
            field=models.IntegerField(default=0),
        ),
    ]
