# Generated by Django 2.2.5 on 2021-11-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20211116_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='forum_credits',
            field=models.FloatField(default=0.0),
        ),
    ]
