# Generated by Django 3.1.4 on 2021-11-07 14:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20211107_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 14, 23, 51, 421085, tzinfo=utc)),
        ),
    ]
