# Generated by Django 2.2.5 on 2021-11-08 08:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('assignments', '0004_auto_20211108_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 12, 48, 612284, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
