# Generated by Django 2.2.5 on 2021-11-08 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_auto_20211108_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 25, 44, 275171, tzinfo=utc)),
        ),
    ]
