# Generated by Django 3.1.4 on 2021-11-08 11:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0006_auto_20211108_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentsubmission',
            old_name='content',
            new_name='comments',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 11, 32, 43, 138449, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Student', to=settings.AUTH_USER_MODEL),
        ),
    ]
