# Generated by Django 2.2.24 on 2021-11-09 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0019_auto_20211109_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 18, 14, 58, 281977, tzinfo=utc)),
        ),
    ]
