# Generated by Django 2.2.5 on 2021-11-10 12:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0020_auto_20211109_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 10, 12, 17, 23, 735841, tzinfo=utc)),
        ),
    ]
