# Generated by Django 2.2.5 on 2021-11-10 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0023_auto_20211110_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 10, 13, 44, 44, 890012, tzinfo=utc)),
        ),
    ]
