# Generated by Django 2.2.5 on 2021-11-13 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0026_auto_20211113_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='assignments.Assignment'),
            preserve_default=False,
        ),
    ]
