# Generated by Django 2.2.5 on 2021-11-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0030_auto_20211113_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='comments',
        ),
    ]
