# Generated by Django 2.2.5 on 2021-11-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0033_auto_20211115_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
