# Generated by Django 2.2.5 on 2021-11-14 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=400, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=400)),
                ('founding_date', models.DateTimeField(auto_now_add=True)),
                ('approval_required', models.BooleanField(default=False)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
