# Generated by Django 2.2.24 on 2021-11-24 13:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0003_eventattendees'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='members',
            unique_together={('club', 'member')},
        ),
    ]
