# Generated by Django 2.2.5 on 2021-11-14 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='booked_seats',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='purchase_time',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_no',
        ),
    ]
