# Generated by Django 2.2.5 on 2021-11-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20211117_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='vaccination_status',
            field=models.CharField(choices=[('Not Vaccinated', 'Not Vaccinated'), ('Partially Vaccinated', 'Partially Vaccinated'), ('Fully Vaccinated', 'Fully Vaccinated')], default='Not Vaccinated', max_length=20),
        ),
    ]
