# Generated by Django 2.2.5 on 2021-11-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_preference_vaccination_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=8),
        ),
    ]
